language: python

python:
  - "3.8"

env:
  - DJANGO=2.2.12
  - postgresql=12.2

install:
  - pip install -r requirements.txt

script:
  - flake8 ./ --max-line-length=130 --exclude=migrations --max-complexity 10
